import Head from "next/head";
import styles from "../styles/Home.module.css";
import CenterThumbnail from "../components/CenterThumbnail";
import Link from "next/link";
export default function Home({ categories }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Quiz App</title>
        <meta name="description" content="Generated by create next app" />
        <meta
          name="google-site-verification"
          content="ChDvQuvKg6XP8i1e6vcxxye5k-7eNziH6COKkn41g2M"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className={styles.header_text}>Choose Category</h1>
      <div className={styles.thumbnail_container}>
        {categories?.trivia_categories.map((category) => (
          <Link
            key={`category_thumbnail_${category.name}`}
            href={`/prequiz?categoryid=${category.id}&categoryname=${
              category.name != "Random" ? category.name : category.value
              }`}
            className={styles.thumbnail_link}
          >

              <CenterThumbnail>
                <p>{category.name}</p>
              </CenterThumbnail>

          </Link>
        ))}
      </div>
    </div>
  );
}
export async function getStaticProps() {
  const res = await fetch("https://opentdb.com/api_category.php");
  let data = await res.json();
  let randint = Math.floor(Math.random() * data.trivia_categories.length);
  data.trivia_categories = [
    { id: -1, name: "Mixed" },
    {
      id: data.trivia_categories[randint].id,
      name: "Random",
      value: data.trivia_categories[randint].name,
    },
    ...data.trivia_categories,
  ];
  return {
    props: {
      categories: data,
    },
  };
}
